apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  config-key: config-value

---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
type: Opaque
data:
  secret-key: c2VjcmV0LXZhbHVl # base64 encoded value
