apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-pod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: three-pod-app
  template:
    metadata:
      labels:
        app: three-pod-app
    spec:
      containers:
        - name: app-container
          image: nginx
